### PR TITLE
Moving _add_dataclass_options() to be a standalone function

### PR DESCRIPTION
**Pull request by jcal-15**
This might be a more controversial change. 😄 I was looking at the new dataclass decorator overload that was implemented. It is a nice concept except that type hinting does not work with it. Since type hinting is the main benefit over normal argparse (In my opinion) I came up with this other approach. 

Not sure how much approach conflicts with your vision of what you want but it seems to offer a similar experience as the dataclass approach while maintaining type hints.

### CODE REVIEW

**Comment by jcal-15** [comment]
For what it is worth, testing is passing now.
https://travis-ci.org/github/mivade/argparse_dataclass/builds/771605697

**Comment by jcal-15** [comment]
Ping.
If you prefer I can break up the pull request into two parts. One for the new tests and fixes for the tests. The other for the new function.

**Comment by mivade** [comment]
Sorry, I've had a lot going on lately and wasn't able to look at this in depth until now. I have no strong opinions on this (I wasn't actually the one using the decorator in the first place) but it looks good enough to me so I'm merging. Thanks for your help!

**Comment by jcal-15** [comment]
> 
> 
> Sorry, I've had a lot going on lately and wasn't able to look at this in depth until now. I have no strong opinions on this (I wasn't actually the one using the decorator in the first place) but it looks good enough to me so I'm merging. Thanks for your help!

Thank you. I am pretty new to contributing to GitHub. I am not sure how long I should wait before pinging someone about a pull request. Feel free to let me know if I pester you too much. 😄 

I have a few more smaller updates in the works. The first is just more tests. The second if a fix for a potential issue with boolean fields.

**Pull request merged**
